version: '3'

services:
  scraper:
    image: tneb-scraper:latest
    container_name: tneb-scraper-script
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: ["poetry", "run", "python", "main.py"]