version: '3'

services:
  scraper:
    image: tneb-scraper:latest
    container_name: tneb-scraper-script
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    
    # # Optionally create a volume with the log path
    # volumes:
    #   - ./debug:/app/debug