name: Publish Docker Image to GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and publish the image
        run: |
          docker login --username infinage --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/infinage/tneb-scraper:latest
          docker push ghcr.io/infinage/tneb-scraper:latest